server:
  port: 8080
  session-timeout: 30
  tomcat:
      max-threads: 0
      uri-encoding: UTF-8

logging:
  level: debug
  path: logs

management:
  port: 8080
#  context-path:
  security:
    enabled: false

spring:
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/anhshop?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username : root
    password : 165177
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : none
      show-sql : true
      jackson.serialization.indent_output : true
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  jta:
    log-dir: logs

  transaction:
    rollback-on-commit-failure: true
    default-timeout: 30
  data:
    solr:
      host: http://localhost:8983/solr/mark
      zk-host:
      repositories:
        enabled: true






